language: scala
scala:
  - 2.13.5
  - 2.12.8
jdk:
  - openjdk11

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - stage: test
    - name: compile
      script: sbt compile
    - name: test
      script: sbt clean coverage test coverageReport
    - name: codecov
      script: bash <(curl -s https://codecov.io/bash)
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release
